
export const bib = `@inproceedings{boyle-etal-2025-cafga,
    title = "CafGa: Customizing Feature Attributions to Explain Language Models",
    author = "Boyle, Alan David  and
      Cheng, Furui  and
      Zouhar, Vilém  and
      El-Assady, Mennatallah",
    editor = {Habernal, Ivan  and
      Schulam, Peter  and
      Tiedemann, Jörg},
    booktitle = "Proceedings of the 2025 Conference on Empirical Methods in Natural Language Processing: System Demonstrations",
    month = "nov",
    year = "2025",
    address = "Suzhou, China",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/2025.emnlp-demos.32/",
    doi = "10.18653/v1/2025.emnlp-demos.32",
    pages = "461--470",
    ISBN = "979-8-89176-334-0",
    abstract = "Feature attribution methods, such as SHAP and LIME, explain machine learning model predictions by quantifying the influence of each input component. When applying feature attributions to explain language models, a basic question is defining the interpretable components.Traditional feature attribution methods, commonly treat individual words as atomic units.This is highly computationally inefficient for long-form text and fails to capture semantic information that spans multiple words.To address this, we present CafGa, an interactive tool for generating and evaluating feature attribution explanations at customizable granularities. CafGa supports customized segmentation with user interaction and visualizes the deletion and insertion curves for explanation assessments. Through a user study involving participants of various expertise, we confirm CafGa{'}s usefulness, particularly among LLM practitioners. Explanations created using CafGa were also perceived as more useful compared to those generated by two fully automatic baseline methods: PartitionSHAP and MExGen, suggesting the effectiveness of the system."
      },
    @inproceedings{boyle2024itotinteractivecustomizedtreeofthought,
      title={iToT: An Interactive System for Customized Tree-of-Thought Generation}, 
      author={Alan Boyle and Isha Gupta and Sebastian Hönig and Lukas Mautner and Kenza Amara and Furui Cheng and Mennatallah El-Assady},
      year={2024},
      booktitle={NLVIZ Workshop at IEEE VIS},
      eprint={2409.00413},
      archivePrefix={arXiv},
      primaryClass={cs.HC},
      url={https://ieeevis.org/year/2024/program/paper_w-nlviz-1019.html}, 
}`